module.exports.transValidation = {
    server_incorrect: " Something went wrong, please wait !!! ",
    upload_incorrect: " Upload image failed , please check your image size !!!",
    input_correct: " Successfully!!",
    email_exist: " Email already in used, please register another email!!",
    login_fail: " Login information is incorrect!!!",
    register_fail: " Register failed!!!",
    admin_fail: "You do not have permission !!!",
    otp_fail: "OTP is not correct !!!",
    otp_expired_timeout: "OTP expired !!!",
    image_fail: "You do not select any image !!!",
    not_found: "Not found!!!",
    upload_correct: "Upload successfull",
    change_password_correct: "Change password successfully",
    password_fail: "Password incorrect, please check again",
    not_login: "You are not login, please login to system !",
    access_token: "Access token GG expired or invalid",
    invalid_token: "Token invalid",
    expired_token: "Token expired",
    bad_request: "Bad request",
    bird_not_exist: "Bird is not exist",
    not_remain_turn: "Your turn is over!!!",
    address_not_exist: "Your address can not be empty",
    game_data_not_exist: "Your data is not exist",
    reward_not_exist: "You do not have reward",
    package_not_exist: "Package is not exist",
    balance_not_enough: "You do not have enough money",
    owner_invalid: "NFT's owner is invalid",
    reward_not_enough: "Not enough amount to claim",
    fee_invalid : "Fee to much",
    bird_not_owner: "You are not owner",
    package_not_valid: "This package invalid",
    txn_pending : "Transaction is pending, please wait",
    wallet_existed : "Wallet existed",
    insert_failed: "Insert DB failed"
};
module.exports.errorCode = {
    server_incorrect: "server_incorrect",
    upload_incorrect: "upload_incorrect",
    input_correct: "input_correct",
    email_exist: "email_exist",
    login_fail: "login_fail",
    register_fail: "register_fail",
    admin_fail: "admin_fail",
    otp_fail: "otp_fail",
    otp_expired_timeout: "otp_expired_timeout",
    image_fail: "image_fail",
    not_found: "not_found",
    upload_correct: "upload_correct",
    change_password_correct: "change_password_correct",
    password_fail: "password_fail",
    not_login: "not_login",
    access_token: "access_token",
    invalid_token: "invalid_token",
    expired_token: "exp_token",
    invalid_address: "invalid_address",
    bad_request: "bad_request",
    user_not_exist: "user_not_exist",
    bird_not_exist: "bird_not_exist",
    not_remain_turn: "not_remain_turn",
    address_not_exist: "address_not_exist",
    reward_not_exist: "reward_not_exist",
    game_data_not_exist: "game_data_not_exist",
    package_not_exist: "package_not_exist",
    balance_not_enough: "balance_not_enough",
    owner_invalid: "owner_invalid",
    reward_not_enough: "amount_not_enough",
    fee_invalid : "invalid_fee",
    bird_not_owner: "bird_not_owner",
    package_not_valid: "package_not_valid",
    txn_pending : "pending_transaction",
    wallet_existed : "wallet_existed",
    insert_failed: "failed_insert"
};

module.exports.responseStatus = {
    success: 'success',
    fail: 'fail',
}